name: 'Workspace'
description: 'Test your workspace'
author: 'lZiMUl'

inputs:
  id:
    description: 'Workspace id'
    required: true

outputs:
  data:
    description: 'Result data output'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'archive'
  color: 'gray-dark'